# Generated by Django 6.0.4 on 2026-04-20 08:20

import secrets

from django.db import migrations, models


def backfill_verification_codes(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    used = set(Certificate.objects.exclude(verification_code__isnull=True).values_list("verification_code", flat=True))
    for cert in Certificate.objects.filter(verification_code__isnull=True):
        code = secrets.token_hex(16).upper()
        while code in used:
            code = secrets.token_hex(16).upper()
        cert.verification_code = code
        cert.save(update_fields=["verification_code"])
        used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_verification_codes, migrations.RunPython.noop),
    ]
